version: "3.5"

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/hmeriann/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/hmeriann/data/mariadb
      o: bind
      type: none


services:
  mariadb:  
    container_name: mariadb_container
    build:
      context: ./mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: ["CMD-SHELL", "mysql dbname -udbuser -pdbpass -e 'SELECT 1;'  || exit 1"]
    #   interval: 2s
    #   retries: 120

  wordpress:
    depends_on:
      - mariadb
      # mariadb:
        # condition: service_healthy
    container_name: wordpress_container
    build:
      context: ./wordpress
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    ports:
      - "9000:9000"
    environment:
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_NICK=${WP_ADMIN_NICK}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER_NICK=${WP_USER_NICK}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - WP_USER_PASS=${WP_USER_PASS}

  nginx:
    depends_on:
      - wordpress
    container_name: nginx_container
    build:
      context: ./nginx
      args:
        SERVER_NAME: ${SERVER_NAME}
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
