CREATE DATABASE IF NOT EXISTS MARIADB_DATABASE;
GRANT ALL ON *.* TO 'MARIADB_USER' IDENTIFIED BY 'MARIADB_PASSWORD' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MARIADB_ROOT_PASSWORD';
FLUSH PRIVILEGES;